#import "../../fragments/gameRandomFactsRoundFields.gql"

query allGameRandomFactsRounds($gameId: Int!) {
  allGameRandomFactsRounds(condition: {gameId: $gameId}) {
    nodes {
      ...gameRandomFactsRoundFields
    }
  }
}
