#import "../../fragments/gameFields.gql"

query allGames($eventId: Int!, $type: GameType) {
  allGames(condition: {eventId: $eventId, type: $type}, orderBy: ID_ASC) {
    nodes {
      ...gameFields
    }
  }
}
