#import "../../fragments/gameRandomFactsRoundFields.gql"

query allGameRandomFactsRounds($gameId: Int!) {
  allGameRandomFactsRounds(condition: {gameId: $gameId}, orderBy: ID_DESC) {
    nodes {
      ...gameRandomFactsRoundFields
    }
  }
}
