#import "../../fragments/gameRandomFactsVoteFields.gql"

query gameRandomFactsVotes($roundId: Int!) {
  allGameRandomFactsVotes(condition: {roundId: $roundId}) {
    nodes {
      ...gameRandomFactsVoteFields
    }
  }
}
