{
  allEvents(orderBy: START_DESC, first: 1) {
    nodes {
      name
      start
      end
      discordInviteCode
      streamUrl
      commonDonationUrl
      teamsByEventId {
        nodes {
          name
          emoji
          charityOrganizationId
          donationUrl
        }
      }
    }
  }
}
