query ($invitationCode: UUID!) {
  playerByInvitationCodeFn(invitationCode: $invitationCode) {
    nodes {
      teamByTeamId {
        name
        emoji
        charityOrganizationId
        donationUrl
        eventByEventId {
          name
          start
          end
          discordInviteCode
          streamUrl
          commonDonationUrl
        }
      }
      name
    }
  }
}
