query ($invitationCode: UUID!) {
  playerByInvitationCodeFn(invitationCode: $invitationCode) {
    nodes {
      teamByTeamId {
        name
        emoji
        charityOrganizationByCharityOrganizationId {
          name
          url
        }
        donationUrl
        eventByEventId {
          name
          start
          end
          discordInviteCode
          streamUrl
          commonDonationUrl
        }
      }
      name
    }
  }
}
